/** OpenAPI-aligned API paths — canonical v1 surface. */

export const API_V1 = '/api/v1' as const

export const paths = {
  auth: {
    login: `${API_V1}/auth/login`,
    me: `${API_V1}/auth/me`,
    users: `${API_V1}/auth/users`,
    changePassword: `${API_V1}/auth/change-password`,
    userEmail: (email: string) => `${API_V1}/auth/users/${encodeURIComponent(email)}`,
    userRole: (email: string) => `${API_V1}/auth/users/${encodeURIComponent(email)}/role`,
    userActive: (email: string) => `${API_V1}/auth/users/${encodeURIComponent(email)}/active`,
    userResetPassword: (email: string) =>
      `${API_V1}/auth/users/${encodeURIComponent(email)}/reset-password`,
  },
  ci: {
    list: `${API_V1}/ci`,
    detail: (id: number) => `${API_V1}/ci/${id}`,
    types: `${API_V1}/ci/types`,
    type: (id: number) => `${API_V1}/ci/types/${id}`,
    exportFull: `${API_V1}/ci/export/full`,
    exportCsv: `${API_V1}/ci/export/csv`,
    exportXlsx: `${API_V1}/ci/export/xlsx`,
    import: `${API_V1}/ci/import`,
    importPreview: `${API_V1}/ci/import/preview`,
    importMapped: `${API_V1}/ci/import/mapped`,
    importCsv: `${API_V1}/ci/import/csv`,
    recycleBin: `${API_V1}/ci/recycle-bin`,
    restore: (id: number) => `${API_V1}/ci/${id}/restore`,
    purge: (id: number) => `${API_V1}/ci/${id}/purge`,
    bulkStatus: `${API_V1}/ci/bulk/status`,
    relations: (id: number) => `${API_V1}/ci/${id}/relations`,
  },
  relations: {
    list: `${API_V1}/relations`,
    detail: (id: number) => `${API_V1}/relations/${id}`,
    types: `${API_V1}/relation/types`,
    type: (id: number) => `${API_V1}/relation/types/${id}`,
    validate: `${API_V1}/relations/validate`,
    exportCsv: `${API_V1}/relations/export/csv`,
    exportXlsx: `${API_V1}/relations/export/xlsx`,
    exportJson: `${API_V1}/relations/export`,
    importCsv: `${API_V1}/relations/import/csv`,
    importJson: `${API_V1}/relations/import/json`,
  },
  resources: {
    search: `${API_V1}/resources/search`,
    resolve: `${API_V1}/resources/resolve`,
    detail: (id: number) => `${API_V1}/resources/${id}`,
    relations: (id: number) => `${API_V1}/resources/${id}/relations`,
    graph: (id: number) => `${API_V1}/resources/${id}/graph`,
    impact: (id: number) => `${API_V1}/resources/${id}/impact`,
    businessPath: (id: number) => `${API_V1}/resources/${id}/business-path`,
    components: (id: number) => `${API_V1}/resources/${id}/components`,
    graphLayout: (id: number) => `${API_V1}/resources/${id}/graph-layout`,
  },
  misc: {
    dashboard: `${API_V1}/dashboard/overview`,
    audit: `${API_V1}/audit`,
    entityAudit: (type: string, id: number) => `${API_V1}/audit/${type}/${id}`,
    constants: `${API_V1}/meta/constants`,
  },
  correlation: {
    ingest: `${API_V1}/correlation/ingest`,
    context: `${API_V1}/correlation/context`,
    ingestLogs: `${API_V1}/correlation/ingest-logs`,
    ingestLog: (id: number) => `${API_V1}/correlation/ingest-logs/${id}`,
  },
  autodiscover: {
    profiles: `${API_V1}/autodiscover/profiles`,
    connectors: `${API_V1}/autodiscover/connectors`,
    connector: (id: number) => `${API_V1}/autodiscover/connectors/${id}`,
    connectorTest: (id: number) => `${API_V1}/autodiscover/connectors/${id}/test`,
    connectorSync: (id: number) => `${API_V1}/autodiscover/connectors/${id}/sync`,
    scan: `${API_V1}/autodiscover/scan`,
    runs: `${API_V1}/autodiscover/runs`,
    run: (runId: number) => `${API_V1}/autodiscover/runs/${runId}`,
    apply: (runId: number) => `${API_V1}/autodiscover/runs/${runId}/apply`,
  },
} as const
