/** AUTO-GENERATED by apps/api/scripts/sync_schema_versions.py — do not edit. */

export const AUTH_SCHEMA_V1 = 'rsm-auth-v1' as const
export const AUTODISCOVER_SCHEMA_V1 = 'rsm-autodiscover-v1' as const
export const CORRELATION_SCHEMA_V1 = 'rsm-correlation-v1' as const
export const INVENTORY_SCHEMA_V1 = 'rsm-inventory-v1' as const
export const META_SCHEMA_V1 = 'rsm-meta-v1' as const
export const OPS_SCHEMA_V1 = 'rsm-ops-v1' as const
export const TOPOLOGY_SCHEMA_V1 = 'rsm-topology-v1' as const

export const SCHEMA_VERSIONS_V1 = {
  auth: 'rsm-auth-v1',
  autodiscover: 'rsm-autodiscover-v1',
  correlation: 'rsm-correlation-v1',
  inventory: 'rsm-inventory-v1',
  meta: 'rsm-meta-v1',
  ops: 'rsm-ops-v1',
  topology: 'rsm-topology-v1',
} as const
