/** AUTO-GENERATED by apps/api/scripts/sync_domain_constants.py — do not edit. */

export const RELATION_TYPES = ['depends_on', 'affects', 'part_of', 'hosted_on', 'uses', 'linked_to', 'reserves'] as const

export const RELATION_TYPE_ALIASES = {'depends on': 'depends_on', 'affects': 'affects', 'part of': 'part_of', 'hosted on': 'hosted_on', 'uses': 'uses', 'linked to': 'linked_to', 'reserves': 'reserves'} as const

export const RELATION_STATUSES = ['active', 'inactive', 'archived'] as const

export const CI_STATUSES = ['active', 'temporarily_disabled', 'decommissioned', 'archived'] as const

export const BULK_CI_STATUSES = ['active', 'temporarily_disabled', 'decommissioned'] as const

export const CRITICALITY_LEVELS = ['critical', 'high', 'medium', 'low'] as const

export const ENVIRONMENTS = ['production', 'pre-production', 'test', 'development'] as const

export const ROLES = ['viewer', 'editor', 'admin'] as const

export const RSM_OFFICIAL_TYPE_NAMES = ['Business Service', 'IT Service', 'Application', 'Technical Component', 'Server', 'Virtual Machine', 'Container', 'Database', 'Queue', 'Network Element', 'External Service'] as const

export const EXTERNAL_ID_FIELDS = ['hostname', 'ip', 'serviceCode', 'applicationCode', 'externalId', 'cmdbId'] as const

export const FIELD_ALIASES = {'host': 'hostname', 'host_name': 'hostname', 'fqdn': 'hostname', 'ip_address': 'ip', 'ipv4': 'ip', 'external_id': 'externalId', 'service_code': 'serviceCode', 'application_code': 'applicationCode'} as const

export type RelationType = (typeof RELATION_TYPES)[number]
export type ExternalIdField = (typeof EXTERNAL_ID_FIELDS)[number]
export type CiStatus = (typeof CI_STATUSES)[number]
export type CriticalityLevel = (typeof CRITICALITY_LEVELS)[number]
export type Environment = (typeof ENVIRONMENTS)[number]
export type Role = (typeof ROLES)[number]
