"""Sync v1 schema_version strings to JSON fixture and web generated TS."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
API_SRC = ROOT / "apps" / "api"
sys.path.insert(0, str(API_SRC))

from src.schemas.v1.versions import SCHEMA_VERSIONS_V1  # noqa: E402

FIXTURE_PATH = ROOT / "fixtures" / "schema-versions.json"
WEB_GENERATED = ROOT / "apps" / "web" / "src" / "shared" / "schemaVersions.generated.ts"


def render_ts(payload: dict[str, str]) -> str:
    lines = [
        "/** AUTO-GENERATED by apps/api/scripts/sync_schema_versions.py — do not edit. */",
        "",
    ]
    for key, value in payload.items():
        const = f"{key.upper()}_SCHEMA_V1"
        lines.append(f"export const {const} = '{value}' as const")
    lines.append("")
    lines.append("export const SCHEMA_VERSIONS_V1 = {")
    for key, value in payload.items():
        lines.append(f"  {key}: '{value}',")
    lines.append("} as const")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(json.dumps(SCHEMA_VERSIONS_V1, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    WEB_GENERATED.write_text(render_ts(SCHEMA_VERSIONS_V1), encoding="utf-8")
    print(f"Wrote {FIXTURE_PATH.relative_to(ROOT)}")
    print(f"Wrote {WEB_GENERATED.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
