"""Sync domain constants from Python source of truth to JSON fixture and web generated TS."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
API_SRC = ROOT / "apps" / "api"
sys.path.insert(0, str(API_SRC))

from src.core.constants import (  # noqa: E402
    CI_STATUSES,
    CRITICALITY_LEVELS,
    ENVIRONMENTS,
    EXTERNAL_ID_FIELDS,
    FIELD_ALIASES,
    RELATION_STATUSES,
    RELATION_TYPE_ALIASES,
    RELATION_TYPES,
    ROLES,
    RSM_OFFICIAL_TYPE_NAMES,
)

FIXTURE_PATH = ROOT / "fixtures" / "domain-constants.json"
WEB_GENERATED = ROOT / "apps" / "web" / "src" / "shared" / "domainConstants.generated.ts"
CONTRACT_GENERATED = ROOT / "packages" / "omnisight-contract" / "src" / "domainConstants.generated.ts"

PAYLOAD = {
    "relation_types": RELATION_TYPES,
    "relation_type_aliases": RELATION_TYPE_ALIASES,
    "relation_statuses": RELATION_STATUSES,
    "ci_statuses": CI_STATUSES,
    "criticality_levels": CRITICALITY_LEVELS,
    "environments": ENVIRONMENTS,
    "external_id_fields": EXTERNAL_ID_FIELDS,
    "field_aliases": FIELD_ALIASES,
    "roles": ROLES,
    "rsm_official_type_names": RSM_OFFICIAL_TYPE_NAMES,
}


def _ts_array(values: list[str]) -> str:
    items = ", ".join(f"'{v}'" for v in values)
    return f"[{items}] as const"


def _ts_record(values: dict[str, str]) -> str:
    items = ", ".join(f"'{k}': '{v}'" for k, v in values.items())
    return f"{{{items}}} as const"


def render_ts(payload: dict) -> str:
    aliases = payload["relation_type_aliases"]
    return f"""/** AUTO-GENERATED by apps/api/scripts/sync_domain_constants.py — do not edit. */

export const RELATION_TYPES = {_ts_array(payload["relation_types"])}

export const RELATION_TYPE_ALIASES = {_ts_record(aliases)}

export const RELATION_STATUSES = {_ts_array(payload["relation_statuses"])}

export const CI_STATUSES = {_ts_array(payload["ci_statuses"])}

export const BULK_CI_STATUSES = {_ts_array([s for s in payload["ci_statuses"] if s != "archived"])}

export const CRITICALITY_LEVELS = {_ts_array(payload["criticality_levels"])}

export const ENVIRONMENTS = {_ts_array(payload["environments"])}

export const ROLES = {_ts_array(payload["roles"])}

export const RSM_OFFICIAL_TYPE_NAMES = {_ts_array(payload["rsm_official_type_names"])}

export const EXTERNAL_ID_FIELDS = {_ts_array(payload["external_id_fields"])}

export const FIELD_ALIASES = {_ts_record(payload["field_aliases"])}

export type RelationType = (typeof RELATION_TYPES)[number]
export type ExternalIdField = (typeof EXTERNAL_ID_FIELDS)[number]
export type CiStatus = (typeof CI_STATUSES)[number]
export type CriticalityLevel = (typeof CRITICALITY_LEVELS)[number]
export type Environment = (typeof ENVIRONMENTS)[number]
export type Role = (typeof ROLES)[number]
"""


def main() -> None:
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    ts_content = render_ts(PAYLOAD)
    FIXTURE_PATH.write_text(json.dumps(PAYLOAD, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    CONTRACT_GENERATED.parent.mkdir(parents=True, exist_ok=True)
    CONTRACT_GENERATED.write_text(ts_content, encoding="utf-8")
    print(f"Wrote {FIXTURE_PATH.relative_to(ROOT)}")
    print(f"Wrote {CONTRACT_GENERATED.relative_to(ROOT)}")
    print(f"Web re-exports via {WEB_GENERATED.relative_to(ROOT)} → @omnisight/contract")


if __name__ == "__main__":
    main()
